#! /bin/sh

sxhkd &

bspc monitor DisplayPort-0 -d I II III IV V
bspc monitor HDMI-A-0 -d VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 38

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a Slack state=floating desktop=^4
bspc rule -a "Toggl Desktop" state=floating
bspc rule -a Steam state=floating
bspc rule -a Zeal state=floating
bspc rule -a "Microsoft Teams - Preview" state=floating dekstop=^4

# Map caps lock to ctrl
setxkbmap -option caps:ctrl_modifier

# Launch lxsession
lxsession &

# Launch picom
picom --experimental-backends -bc &

# Launch polybar
~/.config/polybar/launch.sh

# Launch Dunst for notifications
dunst &

~/.fehbg &
