windowrule = match:class kitty, opacity 0.9 0.8
windowrule = match:class com.mitchellh.ghostty, opacity 0.9 0.8
windowrule = match:class discord, opacity 0.95 0.9
windowrule = match:class firefox, opaque on
windowrule = match:class librewolf, opaque on
windowrule = match:title Warframe, fullscreen on
windowrule = match:class steam, float on
